import './globals.css'
import { Anybody, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const anybody = Anybody({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={anybody.className}>
        <h2>Layout</h2>
        {children}</body>
    </html>
  )
}
